#this one define the format. Each item in the [repos] array is a project. A project may have 0-2 repo, and 0-2 website.
- group_name: group_name
  repos:
  - repo_name: owner/name
    repo2_name: owner/name
    web_name: website name
    web_url: https://www.example.com/
    web2_name:
    web2_url:
    content: this is a description of the projects, or anything else you want to add in the end
    tags:
    # though single tag is much cleaner for organization, it may be hard to classify all projects. At this point, multiple tags are allowed for each project
    - dashboard
    # track current cases, may also include visualization and maps
    - map
    # similar to dashboard, but some may only have a map
    - visualization
    # similar to dashboard, but some may only have visualization of data
    - data
    # collected data (json, yaml, csv, etc) avaliable for further analysis, visualization, or research
    - API
    # data avaliable by curl or wget
    - analysis
    # predictions, timeline review
    - apps
    # applications on andorid or iphones
    - communication
    - community
    - academic
    # related to academic and education
    
